"""Acciones table

Revision ID: 65bb019486a7
Revises: 752508c89e42
Create Date: 2019-11-23 16:55:13.942698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bb019486a7'
down_revision = '752508c89e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('como', sa.String(length=200), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('objetivos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['objetivos_id'], ['objetivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('ontraseña', sa.String(length=128), nullable=False))
    op.drop_column('user', 'contraseña')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contraseña', sa.VARCHAR(length=128), nullable=False))
    op.drop_column('user', 'ontraseña')
    op.drop_table('acciones')
    # ### end Alembic commands ###
