"""Objetivos table

Revision ID: 752508c89e42
Revises: bac4b863224f
Create Date: 2019-11-23 16:05:55.329484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752508c89e42'
down_revision = 'bac4b863224f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objetivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('que', sa.String(length=200), nullable=False),
    sa.Column('porque', sa.String(length=200), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objetivos_fecha_inicio'), 'objetivos', ['fecha_inicio'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objetivos_fecha_inicio'), table_name='objetivos')
    op.drop_table('objetivos')
    # ### end Alembic commands ###
