"""empty message

Revision ID: a0ebd42f3d26
Revises: 
Create Date: 2019-11-26 13:13:43.662368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ebd42f3d26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('lider', sa.Boolean(), nullable=True),
    sa.Column('puesto', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('objetivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('que', sa.String(length=200), nullable=False),
    sa.Column('porque', sa.String(length=200), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objetivos_fecha_inicio'), 'objetivos', ['fecha_inicio'], unique=False)
    op.create_table('acciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('como', sa.String(length=200), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('objetivos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['objetivos_id'], ['objetivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acciones')
    op.drop_index(op.f('ix_objetivos_fecha_inicio'), table_name='objetivos')
    op.drop_table('objetivos')
    op.drop_table('user')
    # ### end Alembic commands ###
